#!/bin/bash
#
# Generate .shortlog file with git commit hash and contributors list
# This file is used by LaTeX to display open source attribution information
#

# Get the directory where the script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# Get the project root (parent of xmScripts)
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Change to project root to ensure git commands work
cd "$PROJECT_ROOT" || exit 1

# Output file (in project root)
OUTPUT_FILE="$PROJECT_ROOT/.shortlog"

# Check if we're in a git repository
if ! git rev-parse --git-dir > /dev/null 2>&1; then
    echo "% Not a git repository" > "$OUTPUT_FILE"
    exit 0
fi

# Get commit hash (short format)
COMMIT_HASH=$(git log -1 --format=%h 2>/dev/null)
if [ -z "$COMMIT_HASH" ]; then
    COMMIT_HASH="unknown"
fi

# Get contributors list (one per line)
# Format: git shortlog -sn outputs "    42  First Last Name"
# We want to skip the number and get everything after it
CONTRIBUTORS=$(git shortlog -sn 2>/dev/null | sed 's/^[[:space:]]*[0-9]*[[:space:]]*//' | sed 's/^[[:space:]]*//' | sed 's/[[:space:]]*$//')

# Generate LaTeX file
cat > "$OUTPUT_FILE" << EOF
% Auto-generated file - do not edit manually
% Generated by: xmScripts/generate_shortlog.sh

% Commit hash
\newcommand{\gitcommithash}{$COMMIT_HASH}

% Contributors list (will be used in itemize environment)
\newcommand{\gitcontributorslist}{%
EOF

# Add each contributor as a list item command
if [ -n "$CONTRIBUTORS" ]; then
    echo "$CONTRIBUTORS" | while IFS= read -r contributor; do
        if [ -n "$contributor" ]; then
            # Escape special LaTeX characters
            contributor=$(echo "$contributor" | sed 's/\\/\\textbackslash{}/g' | sed 's/{/\\{/g' | sed 's/}/\\}/g' | sed 's/\$/\\\$/g' | sed 's/#/\\#/g' | sed 's/\^/\\textasciicircum{}/g' | sed 's/_/\\_/g' | sed 's/%/\\%/g')
            echo "    \item $contributor%" >> "$OUTPUT_FILE"
        fi
    done
else
    echo "    \item (No contributors found)%" >> "$OUTPUT_FILE"
fi

cat >> "$OUTPUT_FILE" << EOF
}
EOF

